version: '3.5'

services:

  # client-app:
  #   container_name: futnews-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - '.:/usr/src/app'
  #     - '/usr/src/app/node_modules'
  #   ports:
  #     - '9090:3000'
  #   environment:
  #     - NODE_ENV=development
  client-app-prod:
    container_name: futnews-app-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production